### ISSUE TITLE
GanImageSegmenter

### ISSUE THREAD

**Issue by alexzhou907** [CSAILVision/gandissect#7]
Is there any code provided for GanImageSegmenter as used in ablate.py?

**Comment by davidbau** [comment]
Cleaned up a couple issues.
1. evalablate.py is the new version of the file ablate.py, so deleted ablate.py.
2. UnifiedParsingSegmenter is the new image segmenter used, so mentioned that in the comments.
3. Updated code for the unified parsing segmenter code so that it can be used on pytorch 1.0+

Fiexd at a529e3cc64e5c9553c802002782351088c892eaf
